language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

before_install:
 # Make sure mono is installed,
 # pipe stdout to dev/null because qq is still too chatty
 - sudo apt-get install -qq software-properties-common > /dev/null
 - sudo add-apt-repository -y ppa:directhex/monoxide
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -y -qq mono-complete ruby-dev ruby-bundler rpm > /dev/null || echo ""
 - mozroots --import --sync
 - bundle

script:
 - rake make