language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

before_install:
 # Make sure mono is installed,
 # pipe stdout to dev/null because qq is still too chatty
 - sudo apt-get install -qq software-properties-common > /dev/null
 - sudo add-apt-respository -y ppa:directhex/monoxide
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -qq mono-complete ruby ruby-rake ruby-bundler > /dev/null
 - mozroots --import --sync
 - bundle

script:
 - rake make